
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=university_guide
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis  # إضافة متغير بيئة لـ Redis
    depends_on:
      - mysql
      - redis  # إضافة اعتماد على خدمة Redis
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: university_guide
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel-network

volumes:
  mysql-data:
    driver: local
  redis_data:
    driver: local

networks:
  laravel-network:
    driver: bridge